import {
    NButton,
    NInput,
    create,
    NGrid,
    NGi,
    NCard,
    NList,
    NListItem,
    NTag,
    NP,
    NH5,
    NButtonGroup,
    NSpace,
    NForm,
    NFormItem,
    NDropdown,
    NDataTable,
    NCollapse,
    NCollapseItem,
    NCheckbox,
    NModal,
    NAffix,
    NIcon,
    NTooltip,
    NInputNumber,
    NInputGroupLabel,
    NInputGroup,
    NBackTop,
    NSkeleton,
    NEllipsis,
    NSelect,
    NPopconfirm,
} from 'naive-ui';
import type { App } from 'vue';

export const installNaive = (app: App<Element>): void => {
    const naive = create({
        componentPrefix: 'n',
        components: [
            NButton,
            NInput,
            NInputGroupLabel,
            NInputGroup,
            NGrid,
            NGi,
            NCard,
            NList,
            NListItem,
            NTag,
            NP,
            NH5,
            NButtonGroup,
            NSpace,
            NForm,
            NFormItem,
            NDropdown,
            NDataTable,
            NCollapse,
            NCollapseItem,
            NCheckbox,
            NModal,
            NAffix,
            NIcon,
            NTooltip,
            NInputNumber,
            NBackTop,
            NSkeleton,
            NEllipsis,
            NSelect,
            NPopconfirm,
        ],
    });

    app.use(naive);
};
