on:
    - push

concurrency:
    group: format-${{ github.ref }}
    cancel-in-progress: true

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.2
              with:
                  version: 7
            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install

            - run: pnpm run format --if-present
            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add --all
                  git diff-index --quiet HEAD || git commit -m "style: format code"
                  git push
